### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by zenna** [wildart/LMDB.jl#1]
Just tried to do the first example from the docs

signal (11): Segmentation fault
mdb_txn_begin at /home/zenna/.julia/v0.3/LMDB/deps/usr/lib/liblmdbjl.so (unknown line)
mdb_txn_start at /home/zenna/.julia/v0.3/LMDB/deps/usr/lib/liblmdbjl.so (unknown line)
start at /home/zenna/.julia/v0.3/LMDB/src/txn.jl:21
julia_start_20503 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
anonymous at no file:3
unknown function (ip: 1799251468)
jl_f_top_eval at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
eval_user_input at REPL.jl:53
jlcall_eval_user_input_20022 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
anonymous at task.jl:95
jl_handle_stack_switch at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
julia_trampoline at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 4199613)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 4199667)
unknown function (ip: 0)
Segmentation fault (core dumped)

**Comment by wildart** [comment]
It looks like you creating a transaction with an invalid environment. Can you provide an exact code you are running?

**Comment by wildart** [comment]
Please, report again if this error will occur.
