### ISSUE TITLE
pointer to invalid memory in MDBValue?

### ISSUE THREAD

**Issue by tanmaykm** [wildart/LMDB.jl#12]
[Here in the `MDBValue` constructor](https://github.com/wildart/LMDB.jl/blob/59ac5ab1542b6248a2771910af727234da610431/src/common.jl#L11-L12), if `val <: Number`, won't the pointer to the array created be invalid after the constructor returns? In that case, that memory region may contain garbage by the time the data gets stored in the database.

**Comment by wildart** [comment]
Yes, it's problem. The value memory could be swept by GC. I guess explicit numeric `MDBValue` type that would hold number will solve this issue.

**Comment by wildart** [comment]
Closed by #14
