### ISSUE TITLE
unable to store types other than Number, String, and Array

### ISSUE THREAD

**Issue by tanmaykm** [wildart/LMDB.jl#13]
It should be possible to use any bits type (including composite types) as keys or values as they have linear representaion in memory.

It seems like a minor change to [`MDBValue` constructor](https://github.com/wildart/LMDB.jl/blob/master/src/common.jl#L12) can enable that.

**Comment by wildart** [comment]
I don't think it is possible for mutable composite types.

**Comment by tanmaykm** [comment]
Yes, only for immutable types.
I have worked out some changes. Sending a PR in a bit.

**Comment by wildart** [comment]
Closed by #14
