### ISSUE TITLE
Failing to build on Gitlab's CI runner

### ISSUE THREAD

**Issue by kylecarbon** [wildart/LMDB.jl#20]
Hi! Just wanted to start by saying thanks for the package -- it's been super useful :)

#### Gitlab CI
I have a project on Gitlab and I'm trying to add LMDB to it. For some reason, it fails to build only on CI. I can use it locally just fine though and it obviously builds in travis. This is part of the `build.log`:

```
$ cat /root/.julia/packages/LMDB/MBmCS/deps/build.log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   122    0   122    0     0   1087      0 --:--:-- --:--:-- --:--:--  1089

100  140k    0  140k    0     0   228k      0 --:--:-- --:--:-- --:--:--  228k
[ Info: Attempting to create directory /shield-ai/general/.julia/packages/LMDB/MBmCS/deps/downloads
[ Info: Downloading file https://github.com/LMDB/lmdb/archive/LMDB_0.9.22.tar.gz
[ Info: Done downloading file https://github.com/LMDB/lmdb/archive/LMDB_0.9.22.tar.gz
[ Info: Attempting to create directory /shield-ai/general/.julia/packages/LMDB/MBmCS/deps/src
[ Info: Attempting to create directory /shield-ai/general/.julia/packages/LMDB/MBmCS/deps
[ Info: Directory /shield-ai/general/.julia/packages/LMDB/MBmCS/deps already exists
[ Info: Attempting to create directory /shield-ai/general/.julia/packages/LMDB/MBmCS/deps/usr/lib
ERROR: LoadError: IOError: could not spawn setenv(`make -j8 -C /root/.julia/packages/LMDB/MBmCS/deps/src/lmdb-LMDB_0.9.22/libraries/liblmdb liblmdb.so`,
...
...
no such file or directory (ENOENT)
```

I created a [MWE repository](https://gitlab.com/kylecarbon/test_lmdb), and here's one of the CI runners that failed to build if you want to see a [fuller log](https://gitlab.com/kylecarbon/test_lmdb/-/jobs/93902409). Any chance you have some thoughts?

#### `build.log` on my local machine
![image](https://user-images.githubusercontent.com/24921149/44948639-2e86e880-add6-11e8-8330-49ee257fdb5c.png)

**Comment by wildart** [comment]
My guess something from CI gcc toolchain is missing (e.g. make or gcc), cause CI crashed on the `make` call.

**Comment by kylecarbon** [comment]
Ah, good call. Fixing it was as simple as adding `apt-get install build-essential` to `.gitlab-ci.yml`. Thanks!
