### ISSUE TITLE
Source file URLS in documentation seem to be local to the build machine

### ISSUE THREAD

**Issue by zot** [wildart/LMDB.jl#21]
The documentation https://wildart.github.io/LMDB.jl/api/LMDB/ source URLs are file URLs, like this: file:///home/art/.julia/v0.4/LMDB/src/env.jl Also, they don't seem to contain line number information.

**Comment by wildart** [comment]
Damn, I guess Documenter.jl at a time of generating these documents had some bugs. Thanks for noticing, I'll rebuild docs.

**Comment by meggart** [comment]
This is fixed in the most recent version of the docs
